Repository locustio/locust, pull requests merged in 2019-10, with the labels that each got.

#665 Exit with code 1 on greenlet exceptions
  locust/main.py
Labels: bug

#1114 Table layout fix to use available space better
  locust/static/style.css
  locust/templates/index.html
Labels: web interface

#484 make sure the current working dir is in the sys.path
  locust/main.py
Labels: documentation, proposal
